export { default as FirstTierPartner } from './FirstTierPartner'
export { MainPartnerCard, MainPartnerPlaceholder } from './MainPartnerCard'
export { default as PartnersList } from './PartnersList'
export { default as PartnersScrollBox } from './PartnersScrollBox'
export { default as SecondTierPartner } from './SecondTierPartner'
