import type { LucideIcon } from 'lucide-react'
import {
  AtSignIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CloudSnow,
  CopyCheckIcon,
  CopyIcon,
  ExternalLink,
  EyeIcon,
  EyeOffIcon,
  HandshakeIcon,
  InfoIcon,
  MailIcon,
  MapPin,
  MenuIcon,
  MountainSnow,
  PencilIcon,
  PlusIcon,
  Snowflake,
  ThermometerSnowflake,
  TrashIcon,
  UserPlusIcon,
  UsersIcon,
  XIcon,
} from 'lucide-react'

import type { IconName } from '@/UI/components/icons/types'

export const iconRenderers: Record<IconName, LucideIcon> = {
  atSign: AtSignIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  cloudSnow: CloudSnow,
  copy: CopyIcon,
  copyCheck: CopyCheckIcon,
  externalLink: ExternalLink,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  handshake: HandshakeIcon,
  info: InfoIcon,
  mail: MailIcon,
  mapPin: MapPin,
  menu: MenuIcon,
  mountainSnow: MountainSnow,
  pencil: PencilIcon,
  plus: PlusIcon,
  snowflake: Snowflake,
  thermometerSnowflake: ThermometerSnowflake,
  trash: TrashIcon,
  userPlus: UserPlusIcon,
  users: UsersIcon,
  xMark: XIcon,
}
