import type { LucideIcon } from 'lucide-react'
import {
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CloudSnow,
  ExternalLink,
  EyeIcon,
  EyeOffIcon,
  HandshakeIcon,
  InfoIcon,
  MailIcon,
  MenuIcon,
  MountainSnow,
  PencilIcon,
  PlusIcon,
  Snowflake,
  TrashIcon,
  UserPlusIcon,
  UsersIcon,
  XIcon,
} from 'lucide-react'

import type { IconName } from '@/UI/components/icons/types'

export const iconRenderers: Record<IconName, LucideIcon> = {
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  cloudSnow: CloudSnow,
  externalLink: ExternalLink,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  handshake: HandshakeIcon,
  info: InfoIcon,
  mail: MailIcon,
  menu: MenuIcon,
  mountainSnow: MountainSnow,
  pencil: PencilIcon,
  plus: PlusIcon,
  snowflake: Snowflake,
  trash: TrashIcon,
  userPlus: UserPlusIcon,
  users: UsersIcon,
  xMark: XIcon,
}
